### ISSUE TITLE
Problems on install

### ISSUE THREAD

**Issue by henricavalcante** [juliangruber/brace-expansion#15]
I've trouble to install mosca and the problem was in this package, after that I try to install manually and that's my output.

```
henricavalcante@henri-srv-01:/usr/lib/node_modules/mosca$ sudo npm install brace-expansion
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "brace-expansion"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/mosca/npm-debug.log
```

debug:

```
...
510 silly generateActionsToTake Starting
511 silly install generateActionsToTake
512 verbose stack TypeError: Cannot read property 'target' of null
512 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
512 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
512 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
512 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
512 verbose stack     at Object.Installer.computeLinked (/usr/lib/node_modules/npm/lib/install.js:411:41)
512 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
512 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
512 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
512 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
512 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
513 verbose cwd /usr/lib/node_modules/mosca
514 error Linux 3.16.0-30-generic
515 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "brace-expansion"
516 error node v5.4.0
517 error npm  v3.5.3
518 error Cannot read property 'target' of null
519 error If you need help, you may report this error at:
519 error     <https://github.com/npm/npm/issues>
520 verbose exit [ 1, true ]
```

**Comment by TrySound** [comment]
Seems like it's npm problem. Try to reinstall npm.
