### ISSUE TITLE
A line in the README brakes jekyll build

### ISSUE THREAD

**Issue by uriklar** [juliangruber/brace-expansion#63]
I have a repo where I deploy to gh-pages using jekyll (using the default Github pages settings, didn't change anything)
I got this error:
```
User
Run actions/jekyll-build-pages@v1
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv109_4ad66e --label 472676 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/REDACTED-icons/REDACTED-icons":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.9
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (line 41): Variable '{{A..C}' was not properly terminated with regexp: /\}\}/ in example/node_modules/brace-expansion/README.md
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 41): Variable '{{A..C}' was not properly terminated with regexp: /\\}\\}/ (Liquid::SyntaxError)
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:128:in `create_variable'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:39:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:114:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:79:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /example/node_modules/balanced-match/README.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.014121623 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.447757663 seconds. Generating: Jekyll::Paginate::Pagination finished in 6.3e-06 seconds. GitHub Metadata: Generating for REPONAME GitHub Metadata: Calling @client.pages("REDACTED/REDACTED-icons", {}) Generating: JekyllRelativeLinks::Generator finished in 0.879152515 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.003033284 seconds. Requiring: kramdown-parser-gfm Generating: JekyllTitlesFromHeadings::Generator finished in 0.067535832 seconds. Rendering: assets/css/style.scss Pre-Render Hooks: assets/css/style.scss Rendering Markup: assets/css/style.scss Rendering: example/node_modules/@babel/parser/CHANGELOG.md Pre-Render Hooks: example/node_modules/@babel/parser/CHANGELOG.md Rendering Markup: example/node_modules/@babel/parser/CHANGELOG.md Rendering Layout: example/node_modules/@babel/parser/CHANGELOG.md Layout source: theme GitHub Metadata: Calling @client.repository("REDACTED/REDACTED-icons", {:accept=>"application/vnd.github.drax-preview+json"}) Rendering: example/node_modules/@emotion/is-prop-valid/CHANGELOG.md Pre-Render Hooks: example/node_modules/@emotion/is-prop-valid/CHANGELOG.md Rendering Markup: example/node_modules/@emotion/is-prop-valid/CHANGELOG.md Rendering Layout: example/node_modules/@emotion/is-prop-valid/CHANGELOG.md Layout source: theme Rendering: example/node_modules/@emotion/memoize/CHANGELOG.md Pre-Render Hooks: example/node_modules/@emotion/memoize/CHANGELOG.md Rendering Markup: example/node_modules/@emotion/memoize/CHANGELOG.md Rendering Layout: example/node_modules/@emotion/memoize/CHANGELOG.md Layout source: theme Rendering: example/node_modules/@emotion/stylis/CHANGELOG.md Pre-Render Hooks: example/node_modules/@emotion/stylis/CHANGELOG.md Rendering Markup: example/node_modules/@emotion/stylis/CHANGELOG.md Rendering Layout: example/node_modules/@emotion/stylis/CHANGELOG.md Layout source: theme Rendering: example/node_modules/@emotion/unitless/CHANGELOG.md Pre-Render Hooks: example/node_modules/@emotion/unitless/CHANGELOG.md Rendering Markup: example/node_modules/@emotion/unitless/CHANGELOG.md Rendering Layout: example/node_modules/@emotion/unitless/CHANGELOG.md Layout source: theme Rendering: example/node_modules/@rollup/pluginutils/CHANGELOG.md Pre-Render Hooks: example/node_modules/@rollup/pluginutils/CHANGELOG.md Rendering Markup: example/node_modules/@rollup/pluginutils/CHANGELOG.md Rendering Layout: example/node_modules/@rollup/pluginutils/CHANGELOG.md Layout source: theme Rendering: example/node_modules/asap/CHANGES.md Pre-Render Hooks: example/node_modules/asap/CHANGES.md Rendering Markup: example/node_modules/asap/CHANGES.md Rendering Layout: example/node_modules/asap/CHANGES.md Layout source: theme Rendering: example/node_modules/async/CHANGELOG.md Pre-Render Hooks: example/node_modules/async/CHANGELOG.md Rendering Markup: example/node_modules/async/CHANGELOG.md Rendering Layout: example/node_modules/async/CHANGELOG.md Layout source: theme Rendering: example/node_modules/color-convert/CHANGELOG.md Pre-Render Hooks: example/node_modules/color-convert/CHANGELOG.md Rendering Mar
```

When I manually removed line 41 from the README the error went away.

**Comment by juliangruber** [comment]
Jekyll shouldn't try to build this module
